algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2023
// Seção de Declarações 
var
Lado,volume:real
inicio
escreval("vamos calcular o volume de um prisma. ")
escreva("informe o primeiro lado do prisma:  ")
leia (lado)
volume<-lado
escreva("informe o segundo lado do prisma:  ")
leia (Lado)
volume<-volume*lado
escreva("informe o terceiro lado do prisma:  ")
leia (Lado)
volume<-volume*lado
escreva(" o volume é de:   ",volume)
fimalgoritmo
