algoritmo "semnome"
// Função :
// Autor :
// Data : 06/08/2023
// Seção de Declarações 
var
n1,n2,n3,n4,n5,res:real
inicio
escreval("forneça um numero:  ")
leia(n1)
escreval("forneça outro numero:  ")
leia(n2)
escreval("forneça outro numero:  ")
leia(n3)
escreval("forneça outro numero:  ")
leia(n4)
escreval("forneça outro numero:  ")
leia(n5)
res<-n1+n2+n3+n4+n5
escreva("o resultado da soma de cada um é:   ",res)
fimalgoritmo
