algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2023
// Seção de Declarações 
var
Lado,lado2,volume:real
inicio
escreval("vamos somar o primeiro com o terceiro numero e multiplicar tudo com o segundo. ")
escreva("informe o primeiro numero:  ")
leia (lado)
volume<-lado
escreva("informe o segundo numero:  ")
leia (Lado2)
escreva("informe o terceiro numero:  ")
leia (Lado)
volume<-((volume+lado)* lado2)
escreva(" o resultado é de:   ",volume)
fimalgoritmo
