algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2023
// Seção de Declarações 
var
Lado,volume:real
inicio
escreval("vamos calcular a media de tres notas. ")
escreva("informe a primeira meida:  ")
leia (lado)
volume<-lado
escreva("informe a segunda media:  ")
leia (Lado)
volume<-volume+lado
escreva("informe a terceira media:  ")
leia (Lado)
volume<-((volume+lado)/3)
escreva(" a media é de:   ",volume)
fimalgoritmo
