algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2023
// Seção de Declarações 
var
Lado,volume:real
inicio
escreval("vamos calcular a multiplicação de tres numeros. ")
escreva("informe o primeiro numero:  ")
leia (lado)
volume<-lado
escreva("informe o segundo numero:  ")
leia (Lado)
volume<-volume*lado
escreva("informe o terceiro numero:  ")
leia (Lado)
volume<-(volume*lado)
escreva(" o resultado é de:   ",volume)
fimalgoritmo
