algoritmo "semnome"
// Função :
// Autor :
// Data : 07/08/2023
// Seção de Declarações 
var
n,n2:real
inicio
escreva("informe um numero:  ")
leia(n)
escreva("informe um outro numero:  ")
leia(n2)
se (n>n2) entao
   escreva(" o primeiro numero é maior")
senao
     se (n=n2) entao
     escreva(" os numeros são iguais")
     senao
     escreva("o segundo numero é maior")
     fimse
fimse
fimalgoritmo
