algoritmo "semnome"
// Função :
// Autor :
// Data : 08/08/2023
// Seção de Declarações 
var
nome1,nome2,nome3,maior_nome:caractere
inicio
escreval("digite um nome")
leia(nome1)
escreval("digite um outro nome")
leia(nome2)
escreval("digite um outro nome")
leia(nome3)
maior_nome<-nome1
se maior_nome<nome2 entao
 maior_nome<-nome2
se maior_nome<nome3 entao
maior_nome<-nome3
fimse
fimse
escreval ("o maior nome é: ",maior_nome)
 fimalgoritmo
